### PR TITLE
RemoteTech Compatibility Patch For Mark IV Spaceplane System

### PR DESCRIPTION
**Pull request by Sandriell**

### CODE REVIEW

**Comment by neitsa** [comment]
Hey @Sandriell , thank you for your PR! Did you have time to test your config file with Mark IV Spaceplane System and KSP 1.2 pre-release? (now that MM is updated for 1.2)

**Comment by Sandriell** [comment]
No, I have not updated to 1.2 at all yet.

**Comment by neitsa** [comment]
@Sandriell : Let me know when you have updated to 1.2 and tested you PR with the latest RemoteTech and KSP versions.

**Comment by KSP-TaxiService** [comment]
@Sandriell Hi, are you able to test your pull request with the latest RT, KSP and MarkIV mods?

**Comment by KSP-TaxiService** [comment]
Hi, I saw that the MarkVI mod was finally updated to KSP 1.3.1 and this pull request is just a config for the drone core of MarkVI system.

I am able to remotely fly the giant baby. Thanks for your contribution!

**Pull request merged**
