### PR TITLE
Building with Visual Studio

### PR DESCRIPTION
**Pull request by PiezPiedPy**
Hard-coded file paths in Visual Studio .csproj file have been removed and replaced with an Environment variable $KSPDEVDIR.
* Allows contributors to have different locations for their development builds. e.g. I use "F:/KSP_DEV/" someone else might use their steam install and another person may use their D Drive, by using an Env Var to point to the install path the .csproj file does not need to be edited to suit each contributors individual preferences.
* Added a bit of info regarding the Env var to the CONTRIBUTING.md file.
* Added build scripts for building with VS: Building with the Release config will create a private Release.zip file and Debug will generate the monodevelop .mdb file for Debugging with breakpoints in VS

We use this scheme with Kerbalism and Trajectories.

Also brought the .csproj file up to date with these changes:
* Toolsversion updated to v.12.
* Un-needed references removed.
* Full Debug symbols for Debug builds.

Updated .gitignore to ignore VS2015+ cache files.

### CODE REVIEW

**Comment by PiezPiedPy** [comment]
The build scripts are aimed at building local zips for a contributors private use. the release script is not essential although the debug script is needed for debugging with breakpoints etc with Visual Studio as it generates the needed .mdb file

**Comment by KSP-TaxiService** [comment]
Hi, may I ask which Visual Studio version are you using? It appears to be 2017.

I have this error when compiling in VS 2015 on my side with KSPDEVDIR setup.
>The OutputPath property is not set for project 'RemoteTech.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='AnyCPU'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.

I tried CI service with VS2017 (no KSPDEVDIR variable) and the same error came out.
>Microsoft (R) Build Engine version 15.7.180.61344 for .NET Framework
>Copyright (C) Microsoft Corporation. All rights reserved.
>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(780,5): error : The OutputPath property is not set for project 'RemoteTech.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='AnyCPU'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\projects\remotetech-2hf2t\src\RemoteTech\RemoteTech.csproj]

Kindly assist to provide some instructions to resolve this error.

**Comment by PiezPiedPy** [comment]
I use VS2017 but the config should work fine with VS2015 as the Trajectories and Kerbalism configs are known to work with VS2015.

If you are using a windows system a newly created Env Var only takes effect after a restart. Also make sure the path you have specified in your Env Var exists.

Note in csproj the OutputPath is defined as:
`<OutputPath Condition="Exists('$(KSPDEVDIR)\GameData\RemoteTech\Plugins\')">$(KSPDEVDIR)\GameData\RemoteTech\Plugins\</OutputPath>`
Your KSPDEVDIR Env Var should point to the root of your install.
screenshot 6

Re the CI build I can add a couple of lines to fix that error. I did not cater for CI in the csproj file, sorry I was not aware you where using it at the time I modified csproj. I will add a commit ;)

**Comment by PiezPiedPy** [comment]
Also your .csproj.user file may have the output dir set, which will override .csproj settings. Maybe try deleting you .user file and restart VS

**Comment by KSP-TaxiService** [comment]
It seems on my side, VS cache on .csproj wasn't fully purged. Only temporary edits to the file forces the cache wiping and I am able to compile fine (after changing another error). Also, KSPDEVDIR env var needs to be in system variables instead of user variables as I use a Windows standard account for daily activities. I will edit your note in `CONTRIBUTING.md` after this.

@PiezPiedPy, is it possible to change these 2 lines of .csproj from `latest` to `default`?
>\<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
>\<LangVersion>**latest**\</LangVersion>
>\</PropertyGroup>

Error came out when I tried to compile.
> CS1617	Invalid option 'latest' for /langversion; must be ISO-1, ISO-2, Default or an integer in range 1 to 6.

>Re the CI build I can add a couple of lines to fix that error. I did not cater for CI in the csproj file, sorry I was not aware you where using it at the time I modified csproj. I will add a commit ;)

Yes, please. This would help too.

**Comment by PiezPiedPy** [comment]
I've changed the language version to default and added a conditional for CI

**Comment by KSP-TaxiService** [comment]
This pull request provides significant improvements over the current and outdated pipeline. 

I will push the necessary changes onto this PR to build successfully in the CI service.

Thanks for helping to streamline the RT build process!

**Pull request merged**
