### PR TITLE
HGR solar panel / antenna

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**

### CODE REVIEW

**Comment by d4rksh4de** [comment]
Is it still needed? I saw that it is included in there https://github.com/Kerbas-ad-astra/HGR-Community-Fixes/blob/master/GameData/HGRCommunityFixes/HGR_RemoteTech.cfg

**Comment by Kerbas-ad-astra** [comment]
I don't want to include it in HGR Community Fixes - I don't use RT and don't want to be responsible for shippng and managing RT patches.

**Comment by d4rksh4de** [comment]
Can't find KSP 1.1.3 compatible version of HGR.

**Comment by Kerbas-ad-astra** [comment]
That's the whole point of HGR Community fixes...

**Comment by d4rksh4de** [comment]
Sorry, I was searching the HGR only, I see now.

**Pull request merged**
