### PR TITLE
Default min crew

### PR DESCRIPTION
**Pull request by Peppie23**
- added a new property to the settings.cfg to define a default min crew for command stations

### CODE REVIEW

**Comment by erendrake** [comment]
Do we want to add checks to make sure that there is at least one crew? or do we think that just having command good enough if they change the setting to 0?

**Comment by erendrake** [comment]
Also this doesnt compile

**Comment by Peppie23** [comment]
oh yea you are right. I pr'ed a fix into ACReeser's branche. (pls merge @ACReeser)

To your question: I am considering that we only should check the given value is an integer and if not than the backup from the backup is 0 :smile: the primary value is the property from our MM Patch. I still do not know exactly how this error occurs.

... maybe it wasn't a good idea from me to put this value into the settings. :/ Because it's not really the `DefaultMinimumCrew` it's more a `BackupMinimumDefaultCrew`. Any change you would make to this field will not take effect until you get this error.

**Comment by erendrake** [comment]
yeah, so this is for when someone else makes an incomplete MM patch? Hmm, i guess making an empty patch could be valid. Maybe we should be more explicit about what is going on when we fall back to this setting?

**Comment by Peppie23** [comment]
let my try this case ...

**Comment by Peppie23** [comment]
:fearful: Every ModuleSPU has this value hard coded https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/master/src/RemoteTech/Modules/ModuleSPU.cs#L39

**Comment by ACReeser** [comment]
Alright, compile fix is merged. Apologies, but I couldn't get the MSBuild expansion dependency on my machine.

Should that hard 6 be replaced with the new setting?

**Comment by Peppie23** [comment]
@ACReeser what version of ksp do you use? 32bit or 64bit?, Win, Linux or Mac?

**Comment by ACReeser** [comment]
32bit Win 8.1

**Comment by erendrake** [comment]
@Peppie23 do we want this? it seems like depending on the module definition is enough for me.

**Comment by erendrake** [comment]
@ACReeser you will have to forgive me, i dont spend nearly enough time in RT land. 

to be clear, the goal of this PR is to allow someone to have a fallback minimum in the case that they did not specify it correctly in the MM cfg? I am not sure i feel the need to support someone not providing a correct module. 

I guess I must have missed the use case for this

**Comment by ACReeser** [comment]
@erendrake it's a fallback for when ```ppms.GetInt("RTCommandMinCrew")``` errors out.  The erroneous behavior is particular to only certain vessels: they are identified as a command station when loaded, but when unloaded RT logs the exception and uses IsCommandStation of false.  This PR proposes using a fallback value of 6 instead of just setting IsCommandStation to false. The root cause of *why* ```ppms.GetInt("RTCommandMinCrew")``` is still unknown.

**Comment by ACReeser** [comment]
To be clear, the module setting would have priority over the default in all but this one (buggy) situation.

**Comment by erendrake** [comment]
More questions, again im sorry i dont follow this stuff closely enough on the forums
    
    they are identified as a command station when loaded, but when unloaded RT logs the exception and uses IsCommandStation of false

Well, if it doesnt work when its not loaded then it never works. ProtoSignalProcessor is only ever built when the craft is not loaded, does "IsRTPowered" have the same problem?

**Comment by ACReeser** [comment]
I do not know about IsRTPowered.

**Comment by ACReeser** [comment]
Since ```ppms.GetBool("IsRTPowered");``` isn't inside the try/catch I believe I would see an uncaught exception if it was broken in the same way, but that is pure conjecture.

I will go looking through the log of my affected vessel to see if the ```catch``` block logs IsRTPowered of false.

**Comment by ACReeser** [comment]
```[LOG 19:06:31.510] RemoteTech: ProtoSignalProcessor(Powered: True, HasCommandStation: True, Crew: 6)```
So on master it pulls the IsRTPowered correctly.

**Comment by erendrake** [comment]
@ACReeser does it always happen with this craft? or is it just the copy you have in your save?

I see now why you wanted to add this and thank you for explaining your reasoning to me. I am worried that having two places where you can specify this number could be confusing and i want to make sure that i understand what is going on first. 

So that we can really track it down would you mind sharing:
* a log file.
* the craft file
* if the craft doesnt always have a problem. would you share your persistence file?

Thank you for your patience

**Comment by ACReeser** [comment]
I'll have to get you the log file later.

[The craft file](https://gist.github.com/ACReeser/7c2c83a3cfaf18ce1403)
[The vessel entry in the save file](https://gist.github.com/ACReeser/0a073178726c9daab61b)

The craft continues to have the problem. It's a multi-part craft, so the whole docking/undocking stuff noted earlier is possibly the root cause.

**Comment by erendrake** [comment]
Thank you. Sorry to drag this out I just need to see if we can root cause
this thing ☺

**Comment by ACReeser** [comment]
No problem! Like I said earlier, I'm just happy to get some visibility on the bug.

**Comment by ACReeser** [comment]
Now that this is reproducible, would it be possible to see if this PR fixes the issue? Would I be able to build my own DLL and try it locally?

**Comment by Peppie23** [comment]
I hope i've fixed #232 with pr #334. So we don't need the backup from the backup variable. But thanks @ACReeser for your work. I'll close this pr that i can delete Branche 1.6.

**Pull request closed without merging**
