### PR TITLE
1.7.0 Allow groundstations to be created ingame/via api

### PR DESCRIPTION
**Pull request by legacynl**
Hello,
I thought it would be cool to have a way of adding groundstations via API. This would allow for example KerbalKonstructs to add functional remotetech groundstations in newly opened bases. 

Couple of notes:
- This is my first time making a pull request and using git(hub) in general. I'm very new to this, but I'm willing to learn. If I made a mistake, please don't hesitate to call me out on it.
- I'm using monodevelop on linux, and it has problems with default arguments so for it to compile I've had to change all the RTLog.Notify("something"); into RTLog.Notify("something", RTLogLevel.x)11

### CODE REVIEW

**Comment by Peppie23** [comment]
Hi @legacynl 
i've created a pr on your side to fix the merge conflict. Please look that your branche is always up to date with the branche you want to add a new feature.

**Comment by Peppie23** [comment]
@legacynl i've create a new merge fix on your fork. Can you please merge this as well? My pull requests from today: #502 cause this conflict with your branche.

**Comment by legacynl** [comment]
@Peppie23 I merged your pr's. There was a bug where I was able to remove KSC, because Guid.ToString() defaults to show hyphens(-), but I believe it works right now. Do I need to make another pull request?

**Comment by Peppie23** [comment]
@legacynl no your last pr is registered. Btw thx for this feature.

**Pull request merged**
