### PR TITLE
Add config file for procedural probe cores

### PR DESCRIPTION
**Pull request by MichielBijl**
Straight forward me thinks.

### CODE REVIEW

**Comment by MichielBijl** [comment]
It's almost been a month, is there something wrong with this PR?

**Comment by tomekpiotrowski** [comment]
Can you re-test this with KSP 1.1 and RemoteTech from develop?

**Comment by MichielBijl** [comment]
Will do now that 1.1 is final.

**Comment by amedee** [comment]
You'd might want to test with 1.1.2.

**Comment by MichielBijl** [comment]
Yes, I need to setup my KSP with the mods again.

**Comment by MichielBijl** [comment]
I have retested this to work with:

RemoteTech v1.7.0
[ProceduralParts v1.2.3](https://github.com/Swamp-Ig/ProceduralParts/releases/tag/v1.2.3)
[ProceduralProbes v1.1](http://mods.curse.com/ksp-mods/kerbal/233798-proceduralprobes)
ModuleManager.2.6.24

Good to go 👍

**Comment by tomekpiotrowski** [comment]
Thanks!

**Pull request merged**
