### PR TITLE
Update part.cfg

### PR DESCRIPTION
**Pull request by Y3mo**

### CODE REVIEW

**Comment by tomekpiotrowski** [comment]
why do you want to change the masses of all those parts?

**Comment by Y3mo** [comment]
Currently the RT dishes are extremely heavy, not only in comparison to the stock KSP parts, but even in comparison to real life.

**Comment by tomekpiotrowski** [comment]
Can you make a single PR out of the 4 you've submitted? It would make things easier for us to follow.

**Comment by Y3mo** [comment]
I ll try.

With the old masses, there was little incentive to use RT parts, especially when compared to stock parts.

The proposed values are take from the SETIrebalance mod, where they have been very well recieved for over a year.

**Pull request closed without merging**
