### PR TITLE
Fix Ven's Stock Revamp Antennas

### PR DESCRIPTION
**Pull request by Fumblesneeze**
These Modules seem to be required for the dishes to work.

### CODE REVIEW

**Comment by KSP-TaxiService** [comment]
Hi, 

Without these modules, the revamped antennas do not work properly under RT om KSP 1.3?

**Comment by Fumblesneeze** [comment]
They did not work for me, latest CKAN install of RT. Dishrange in flight was 0.

**Comment by KSP-TaxiService** [comment]
Hmmm, it seems to work fine with RT develop and Stock Part Revamp 1.9.6. I can see the dish range is not 0. Can I see your output_log.txt please?

image

**Comment by Fumblesneeze** [comment]
I won't have time to try until sometime next week.

**Comment by Fumblesneeze** [comment]
dish
this is using 1.8.8

**Comment by KSP-TaxiService** [comment]
Thanks. I compared the antenna cfgs of RT and third-party antennas and found the mentions of `ModuleSPUPassive` everywhere. Although it works with and without this tag on my side, I trust the other cfgs and your words that this PR will solve the issue.

**Comment by Fumblesneeze** [comment]
Thanks,

As I said, I have no idea what this actually does, I’m not affiliated with either RT or Ven’s Stock Revamp. Maybe it’s some combination of other mods like Kopernicus that requires this module.

Thanks for merging though.

Von: TaxiService [mailto:notifications@github.com]
Gesendet: Montag, 28. August 2017 15:20
An: RemoteTechnologiesGroup/RemoteTech
Cc: Fumblesneeze; Author
Betreff: Re: [RemoteTechnologiesGroup/RemoteTech] Fix Ven's Stock Revamp Antennas (#737)


Thanks. I compared the antenna cfgs of RT and third-party antennas and found the mentions of ModuleSPUPassive everywhere. Although it works with and without this tag on my side, I trust the other cfgs and your words that this PR will solve the issue.

**Pull request merged**
