### PR TITLE
Config for Ven's Stock Part Revamp Antennas

### PR DESCRIPTION
**Pull request by icedown**
This adds antenna configs for the new antennas added by Ven's Stock Part Revamp.  I think they are inline with their size vs the RemoteTech ones.

### CODE REVIEW

**Comment by neitsa** [comment]
@icedown Thanks for your PR! Did you tested your config file with KSP 1.2 pre-release?

**Comment by neitsa** [comment]
Just bumping the Pull requests to see if there's any news. Let me know @icedown when you have tested your PR with the latest KSP and RemoteTech versions (at least if you plan to update to those versions). 

Thanks!

**Comment by Sandriell** [comment]
This already exists in the mod. See https://github.com/RemoteTechnologiesGroup/RemoteTech/pull/662

**Comment by KSP-TaxiService** [comment]
Thanks, Sandriell for pointing out this.  Since the patch for Ven's stock revamp is already in the RT 1.8.0 and later versions, I will close this pull request.

**Pull request closed without merging**
