### PR TITLE
add whitelist for ReStock

### PR DESCRIPTION
**Pull request by Gordon-Dry**
affected:
Squad/Parts/Utility/commsDish16/
Squad/Parts/Command/probeStackSphere/

### CODE REVIEW

**Comment by KSP-TaxiService** [comment]
Hi, what is the purpose of this new file?

**Comment by Gordon-Dry** [comment]
When the mod ReStock is used, there is a blacklist and a whitelist.

The references mentioned above are used by RT and blacklisted by ReStock.
So the models / textures would not be available.

The whitelist files reverts that.

**Comment by Gordon-Dry** [comment]
... or you could make RT use the Restock replacements instead if the stock parts.

**Comment by Gordon-Dry** [comment]
Well, I see there is a
GameData\RemoteTech\RemoteTech_Restock_Antennas.cfg
but without the whitelist the antenna was not loaded correctly in KSP boot.

**Comment by KSP-TaxiService** [comment]
Yah, `RemoteTech_Restock_Antennas.cfg` was included in RT 1.9.2 to use ReStock replacements. It should work fine at your end.

**Comment by KSP-TaxiService** [comment]
Closing this pull request with necessary changes already in or added

**Pull request closed without merging**
