### PR TITLE
Increase maximum multiplier

### PR DESCRIPTION
**Pull request by madman2003**
Be more friendly towards realistic wordscale games.
FYI, i could not stop git from doing something to the line endings of that config file.

### CODE REVIEW

**Comment by madman2003** [comment]
For reference, the orbit height of a KEO satellite is over 10 MM, with a semi major axis of close to 17 MM. If I want to have a 32 antenna connect with a 16-S with the root square model, I need to be able to cover in the order of 20 MM. And a factor 5 is scarily close to that figure (starting from the baseline 4MM).

**Comment by madman2003** [comment]
I made a mistake due to 1d not matching the rotation of Kerbin. It gets even even worse, the semi major axis is above 26MM. And the satellite distance is around 45MM for a set of 3 in KEO orbit. Running with multiplier 10 that works.

FYI: For some reason 32 to 32 communication is listed as 50MM range in game (despite https://remotetechnologiesgroup.github.io/RemoteTech/guide/settings/#world-scale suggesting 100), and 16-S to 32 is listed as 15MM range (despite https://remotetechnologiesgroup.github.io/RemoteTech/guide/settings/#world-scale suggesting 40)

**Comment by KSP-TaxiService** [comment]
Hi madman2003. 

Thanks for your contribution! I verified your changes are working at my end.

For your range queries, one antenna's range displayed in-game is not a result of Range Model between itself and another antenna. It is its own max range. For example, the max range of Comm 32 is 5Mm * 10 multipler = 50Mm. Likewise, 16-S's max range is 1.5Mm * 10 multipler = 15Mm.

So Range Model will take in the max ranges of 2 antennas and compute the max range between them in background.

Do you have any further question? If not, I will merge your commits into RT codebase.

**Comment by madman2003** [comment]
Answers are clear, push the button when you're ready ;-)

**Pull request merged**
