### PR TITLE
Fix for register a station after unload

### LINKED ISSUE #232: Ground base loses Remote Guidance status on unload
Posted in the forum (http://wee.sk/1wL2UL6), reposting here by request:

--

I'm having an issue with the Remote Guidance Unit. It seems to work fine whenever the base is within loading distance, but then the base stops being a viable command post once I'm high in orbit.

I set up a base on Minmus: Ten Kerbals in four ships interlinked by (docked) KAS winches. One of those ships has the guidance unit, as well as omnis and dishes. I've been launching comsats from that base (using Extraplanetary Launchpads) and they've been operating fine. During takeoff, they maintain line-of-sight with the base, and the base is considered a command post, with the red dot on the orbital map view.

But at some point while I was doing corrections with my satellite in a 2,000,000m orbit around Minmus, I realised that I was losing connection every time Mission Control went around the other side of Kerbin — I haven't set up satellites around Kerbin yet. The red dot was gone, and even though I confirmed I had an omni link to Minmus base, I wasn't getting control. Switched to the base, red dot back. Switched to the satellite, red dot gone.

--

More testing: I waited until KSC went behind Kerbin and we lost contact, then launched a super simple probe.  Octo2, radioisotope generator, communotron 32 (active), engine.  Lost control very quickly during ascent, i.e. as soon as the base fell outside 3km and was unloaded.  Interestingly, I also lost omni connectivity with the ground base (all satellites did), but only temporarily; going back to the space center, then coming back to the satellite, I see everyone (including my test craft) has contact with Minmus Base, yet I still don't have control, and the red dot is still gone.

KSP.log just after launching a second test craft and losing contact: https://dl.dropboxusercontent.com/u/32378574/remotetech-guidance-bug.log

Of particular note is that the Chatterer RemoteTech integration throws exceptions at the moment of unload:

```
[EXC 21:26:32.827] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
        System.Collections.Generic.List`1[RemoteTech.ISignalProcessor].get_Item (Int32 index)
        RemoteTech.VesselSatellite.get_SignalProcessor ()
        RemoteTech.VesselSatellite.get_Guid ()
        RemoteTech.API.<HasConnectionToKSC>m__0 (RemoteTech.NetworkRoute`1 r)
        System.Linq.Enumerable.Any[NetworkRoute`1] (IEnumerable`1 source, System.Func`2 predicate)
        RemoteTech.API.HasConnectionToKSC (Guid id)
        Chatterer.chatterer.updateRemoteTechData ()
        Chatterer.chatterer.Update ()
```

However, disabling Chatterer integration doesn't fix it.

Savefile: https://dl.dropboxusercontent.com/u/32378574/remotetech-guidance-bug.sfs

My modlist (bold = I know my save uses parts from this):
* Asteroid Recycling Technologies 0.5.3
* Better Atmospheres 5.0
  * Custom Asteroids 1.1.0
  * DistantObject 1.3.1
  * EnvironmentalVisualEnhancements 7.4-LR
  * TextureReplacer 1.7.3
  * KittopiaTech Planetary Editing Tools 0.18
* Chatterer 0.7.1
* Contract Plus Window 2.2
* CustomBiomes 1.6.7
* DMagic Orbital Science 0.8.6.1
* Deadly Reentry 6.2.1
* Ferram Aerospace Research (FAR) 0.14.3.2
* Fine Print 0.59
* **Kerbal Attachment System (KAS) 0.4.9**
* **Karbonite 0.4.2**
* **Extraplanetary Launchpads 4.3.1**
  * **Karbonite ExtraPlanetaryLaunchpads conversion 16.7**
  * custom EPL-Karbonite-Conversion.cfg from Nori (http://wee.sk/1000XMA)
* Infernal Robotics 0.19.2
* **MechJeb2 2.4.0.0**
* Precise Node 1.1.1
* Procedural Fairings 3.10
* RealChute Parachute Systems 1.2.5.3
* **RemoteTech 1.5.1**
* Romfarer LazorDockingCam v34
* SCANsat v8
* Soundtrack Editor 2.1a
* Toolbar 1.7.7
* TweakScale 1.44
* Universal Storage
  * US Core 0.9.0.242
  * US KAS 0.9.0.141
* Vanguard Technologies EVA Parachute 1.2
  * VNG Plugin 0.7.2
  * automatic enabling of parachutes for all EVAs (http://wee.sk/1001gH5)
* Active Texture Management

### PR DESCRIPTION
**Pull request by Peppie23**
The `v.GetVesselCrew().count` returns 0 on a `ProtoSignalProcessor`. Thats why i'll look into the `v.protoVessel` to get the crew count.
Fixes #232 

I also added an exception logging for the `getInt` problem.

### CODE REVIEW

**Comment by wisq-minted** [comment]
:godmode: :+1: :tada:

**Comment by Peppie23** [comment]
@wisq-minted you can use this version: https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/build-master-272

**Comment by Norgg** [comment]
Yay!

**Comment by ACReeser** [comment]
Do you have a lead on the getInt problem?

**Comment by ACReeser** [comment]
I tried that build and it did not fix the issue that I had with #232.

**Comment by ACReeser** [comment]
@Peppie23, apologies, you are entirely correct: I had missed that it was Chatterer causing #232 , in fact I missed that entirely when entering my notes a month ago! 

I should have put in a new issue.

**Pull request merged**
