### PR TITLE
VDS Hullcam Support

### PR DESCRIPTION
**Pull request by schnip**
The VDS Hullcam mod adds the Pictozoom 2000, and it need a config to work with RemoteTech. So, I made one.

### CODE REVIEW

**Comment by d4rksh4de** [comment]
Can you please remove all other changes and leave only the .cfg.

**Comment by schnip** [comment]
Oops, I don't know for that second commit snuck in there.

**Comment by schnip** [comment]
Should be good to go

**Comment by d4rksh4de** [comment]
Can't find 1.1.3 compatible release of VDS Hullcam.

**Comment by neitsa** [comment]
@schnip : I see that Hullcam VDS is now updated for KSP 1.2 ([forum link here](http://forum.kerbalspaceprogram.com/index.php?/topic/145633-12-hullcam-vds-continued/)). Could you please test if your patch still applies to the 1.8.0 release?

**Comment by KSP-TaxiService** [comment]
No issue in my testing is found. Seeing this is just a support config for the probe-core part of the mod, I go ahead and accept this pull request. 

Thanks for your contribution!

**Pull request merged**
