### PR TITLE
Stockalike Station Parts Expansion support

### PR DESCRIPTION
**Pull request by Darkenator**
Config for station cores from Stockalike Station Parts Expansion.

http://forum.kerbalspaceprogram.com/index.php?/topic/82833-112-stockalike-station-parts-expansion-01062016-112-update/

### CODE REVIEW

**Comment by Darkenator** [comment]
It under development. I'll let you know as soon it will be updated.

**Comment by neitsa** [comment]
Hi @Darkenator : It seems that [Stockalike Station Parts Expansion](http://forum.kerbalspaceprogram.com/index.php?/topic/82833-12-stockalike-station-parts-expansion-oct-21-12-update/) as been updated for KSP 1.2. Could you please test with the latest KSP release and RemoteTech 1.8.0 if your PR still works or not?

Thanks!

**Comment by Darkenator** [comment]
Hi @neitsa.

Thanks for reminding. Seems stable version for 1.1.3 didn't release at all.

I tested bouth parts on KSP 1.2 from Steam. Communication is established, the internal antenna works, control via the mobile control center works too. So it works.

But I noticed one thing. Control via the mobile center works even when the control vessel is uncontrollable. Crew on board, but not have link to Kerbin and any comandpod, only probecore. This is normal behavior?

**Comment by neitsa** [comment]
Hi @Darkenator 

>But I noticed one thing. Control via the mobile center works even when the control vessel is uncontrollable. Crew on board, but not have link to Kerbin and any comandpod, only probecore. This is normal behavior?

If you mean you have a vessel which have:
* A Kerbalmax RGB-2 'Distributor' Station Core (from Stockalike Station Parts Expansion)
 * Note: according to your PR this part acts as a **command station**
* At least six kerbals on the vessel (anywhere on the vessel, not necessarily in a command pod)

Then yes, the vessel is **not** subjected to any delay and is directly (locally) controllable. 

Does this shows up in the RT quadrant status (below the time quadrant) as your ship having local control?
If not could you post a screenshot of your vessel so I could see exactly what going on?

Thanks!

**Comment by Darkenator** [comment]
That's right. I see red button of flight computer and local control status with no delay on RGB-2.

**Comment by neitsa** [comment]
@Darkenator : ok, so this is the intended behavior (this was addressed in #633) : Command stations can now control themselves if they are properly crewed.

If you think your PR is correct as is (the behavior seems correct to you), tell me and I will merge your PR immediately. 

Thanks a lot for your work!

**Comment by Darkenator** [comment]
Looks like all works fine, merge it please.

Thanks!

**Comment by neitsa** [comment]
Thanks a lot for your PR! It will be added to the changelog and integrated in 'master' for the next minor release (1.8.1).

**Pull request merged**
